### PR TITLE
Increase font size and add more resources

### PR DESCRIPTION
**Pull request by foxted**
Increased font size (was looking really small on a retina display) & created more resources: 

- [x] Number of species
- [x] Wood
- [x] Water

Also, assign a random values for the following: 

- [x] Metal
- [x] Wood
- [x] Water
- [x] Food
- [x] Weaponary

### CODE REVIEW

**Comment by zac-garby** [comment]
Nice one :) I like the idea for "Number of species"

**Comment by zac-garby** [comment]
Do you think you could add the new resource types to the "Ship Designer" sidebar?

**Comment by foxted** [comment]
I’ll see what I can do, just getting back into C++ after many years 😂

**Comment by zac-garby** [comment]
Thanks 👍  It shouldn't be too hard - have a look at the definition for `ShipDesigner` to see how it's done at the moment.

**Pull request merged**
