### PR TITLE
added acceleration term in spaceship.cpp

### PR DESCRIPTION
**Pull request by alphaWizard**
attribute SHIP_ACCELERATION causes the ship to give a term responsible for acceleration of spaceship

### CODE REVIEW

**Comment by zac-garby** [comment]
Where's `SHIP_ACCELERATION` defined?

What difference does this change make to the movement of ships?

**Comment by alphaWizard** [comment]
SHIP_SPEED gives linear increase in distance but SHIP_ACCELERATION will give quadratic increase in motion as the term 1/2*a*t*t. SHIP_ACCELERATION will have to be defined similar way as SHIP_SPEED.

**Comment by zac-garby** [comment]
Ah, I see - could you define it then?

**Comment by alphaWizard** [comment]
in which file it is?

**Comment by zac-garby** [comment]
`config.h`

**Comment by alphaWizard** [comment]
added SHIP_ACCELERATION 10.
its is an estimate that may work(because time square will increase faster therefore 10)  and can be adjusted suitably.

**Comment by zac-garby** [comment]
Have you tested this? Does it work properly?

**Pull request closed without merging**
