### PR TITLE
add functional to fix compilation error

### PR DESCRIPTION
**Pull request by 0x72D0**

### CODE REVIEW

**Comment by zac-garby** [comment]
What does `<function>` do, and what was the compilation error?

**Comment by 0x72D0** [comment]
my compilation error was:
/home/kts/solar-system/widget.h:74:10: error: ‘function’ in namespace ‘std’ does not name a template type
     std::function<void ()> callback;

so I did a little research and the functional header was missing, this header include the std::functional. Now I can compile the code.

**Comment by zac-garby** [comment]
Oh, nice :) Is it necessary to `include <functional>` in that many files though?

It seems to me the problem is that on some platforms, you need to `include <functional>` to use the `std::function` type - however I'm only actually using that type in a handful of files.

**Comment by 0x72D0** [comment]
I added the fuctional header on every file I receive the compilation error.

**Comment by zac-garby** [comment]
I think that only about 2 files actually need the include. Could you try removing it from files, and seeing for which ones the error returns?

**Comment by 0x72D0** [comment]
Yeah sorry I just discover that adding it to widget.h only actually solve this problem... I'm gonna change the pull request

**Comment by zac-garby** [comment]
Cool, thanks 👍

**Comment by 0x72D0** [comment]
ok I've got problem with my github repo... I'm gonna open a new pull request...

**Pull request closed without merging**
